<a href="https://colab.research.google.com/github/444-Mayavathi/Mayaraj-/blob/main/exp_no_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pattern = r'\s'
data['twits'].apply(lambda x: re.sub(pattern, '', x)
mmayavathi90@gmail.com

In [ ]:
import pandas as pd
import numpy as np
import re

In [ ]:
data_out = pd.read_csv('/content/twitter4000.csv')

In [ ]:
data_out

                                                 twitts  sentiment
0     is bored and wants to watch a movie  any sugge...          0
1              back in miami.  waiting to unboard ship           0
2     @misskpey awwww dnt dis brng bak memoriessss, ...          0
3                     ughhh i am so tired  blahhhhhhhhh          0
4     @mandagoforth me bad! It's funny though. Zacha...          0
...                                                 ...        ...
3995                                  i just graduated           1
3996          Templating works; it all has to be done            1
3997                   mommy just brought me starbucks           1
3998  @omarepps watching you on a House re-run...lov...          1
3999  Thanks for trying to make me smile I'll make y...          1

[4000 rows x 2 columns]

In [ ]:
pattern = r'\w+@\w+.\w+'

In [ ]:
pattern = r'b[A-Za-z._+-]+@[A-Za-z.][A-Z|a-z]{2,} \b]'

In [ ]:
data_out['twitts'].apply(lambda x: re.findall(pattern=pattern, string=x))

0       []
1       []
2       []
3       []
4       []
        ..
3995    []
3996    []
3997    []
3998    []
3999    []
Name: twitts, Length: 4000, dtype: object

In [ ]:
pattern = r'http\S+|www|S+'

In [ ]:
data_int = pd.read_csv('/content/twitter4000.csv')

In [ ]:
pattern = r'\b[A-Za-z0-9.%+-]+@[A-ZA-Za-z0-9.-]+\.[A-Z|a-z]{2.}\b'
data_int['email'] = data_int['twitts'].apply(lambda x: re.findall(pattern=pattern, string=x))

In [ ]:
data_int['email'].value_counts()

email
[]    4000
Name: count, dtype: int64

In [ ]:
data_int['email']

0       []
1       []
2       []
3       []
4       []
        ..
3995    []
3996    []
3997    []
3998    []
3999    []
Name: email, Length: 4000, dtype: object